import Head from "next/head";
import { useEffect, useState } from "react";
import Halloween from "../components/Halloween";

function Home() {

  return (
    <>
      <Head>
        <title>CountDown Timer</title>
        <meta name="Countdown Timer" content="Generated by create-t3-app. Created by Kat Lea" />
      </Head>

      <Halloween />
    </>
  );
};

export default Home;

