import type { NextPage } from "next";
import Head from "next/head";
import Moon from "../components/MoonBackground";
import Timer from "../components/Timer";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>CountDown Timer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="img/FullMoon.png" />
      </Head>

      <Moon />

      <Timer />
    </>
  );
};

export default Home;

